# Generated by Django 5.2.5 on 2025-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('pants', 'Pants'), ('pad', 'Pad'), ('headwear', 'Headwear'), ('gloves', 'Gloves'), ('ball', 'Ball'), ('bag', 'Bag'), ('bottle', 'Bottle'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
